import { describe, expect, test } from 'vitest'
import { extractAnswerKeyFromImage } from '../src/answer-key-comparator'

describe('Test File answer-key-comparator', () => {
  test('should extract answer key successfully', async () => {
    const answerKey = await extractAnswerKeyFromImage('answer-key-1-answer.jpg')
    expect(answerKey).toEqual({
      '1': 'b',
      '2': 'c',
      '3': 'c',
      '4': 'b',
      '5': 'c',
      '6': 'd',
      '7': 'a',
      '8': 'b',
      '9': 'a',
      '10': 'a',
      '11': 'c',
      '12': 'c',
      '13': 'a',
      '14': 'c',
      '15': 'c',
      '16': 'a',
      '17': 'a',
      '18': 'b',
      '19': 'a',
      '20': 'b',
      '21': 'c',
      '22': 'b',
      '23': 'd',
      '24': 'b',
      '25': 'c',
      '26': 'a',
      '27': 'd',
      '28': 'd',
      '29': 'b',
      '30': 'b',
      '31': 'c',
      '32': 'c',
      '33': 'c',
      '34': 'b',
      '35': 'a',
      '36': 'c',
      '37': 'b',
      '38': 'd',
      '39': 'a',
      '40': 'b',
      '41': 'a',
      '42': 'b',
      '43': 'a',
      '44': 'c',
      '45': 'b',
      '46': 'a',
      '47': 'c',
      '48': 'a',
      '49': 'c',
      '50': 'c',
      '51': 'c',
      '52': 'd',
      '53': 'a',
      '54': 'b',
      '55': 'a',
      '56': 'a',
      '57': 'b',
      '58': 'c',
      '59': 'c',
      '60': 'a'
    })
  }, 10_000)
})
